---
title: 'Encontrando o seu Ikigai '
author: Eric Nice
email: contato@ericnice.com
description: 'Entre comigo nesta jornada para descobrir o seu Ikigai. '
baseurl: ''
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
